apiVersion: v1
kind: Service
metadata:
    name: qarc-algofactory-service
spec:
    type: ClusterIP
    selector:
        app: qarc-algofactory
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443